services:
  backend-api:
    build:
      context: ../../ProjekAbsenta/backend/absenta_backend
      dockerfile: Dockerfile
    image: absenta-backend:latest
    container_name: absenta-backend-api
    env_file:
      - ../env/env.common
      - ../env/env.database
      - ../env/env.redis
      - ../env/env.payment
      - ../env/env.email
      - ../env/env.production
    environment:
      - NODE_NAME=node-api
      - EMBEDDED_WORKERS=false
    ports:
      - "3001:3001"

  worker-infra:
    image: absenta-backend:latest
    container_name: absenta-worker-infra
    env_file:
      - ../env/env.common
      - ../env/env.database
      - ../env/env.redis
      - ../env/env.production
    environment:
      - NODE_NAME=node-api
    command: ["node","dist/workers/infra.worker.js"]

  worker-agent:
    image: absenta-backend:latest
    container_name: absenta-worker-agent
    env_file:
      - ../env/env.common
      - ../env/env.database
      - ../env/env.redis
      - ../env/env.production
    environment:
      - NODE_NAME=node-api
    command: ["node","dist/infra/workerAgent.js"]

  worker-billing:
    image: absenta-backend:latest
    container_name: absenta-worker-billing
    env_file:
      - ../env/env.common
      - ../env/env.database
      - ../env/env.redis
      - ../env/env.production
    environment:
      - NODE_NAME=node-billing
    command: ["node","dist/workers/billing.worker.js"]

  worker-notification:
    image: absenta-backend:latest
    container_name: absenta-worker-notification
    env_file:
      - ../env/env.common
      - ../env/env.database
      - ../env/env.redis
      - ../env/env.production
    environment:
      - NODE_NAME=node-billing
    command: ["node","dist/workers/notification.worker.js"]

  worker-attendance:
    image: absenta-backend:latest
    container_name: absenta-worker-attendance
    env_file:
      - ../env/env.common
      - ../env/env.database
      - ../env/env.redis
      - ../env/env.production
    environment:
      - NODE_NAME=node-attendance
    command: ["node","dist/workers/attendance.worker.js"]

  worker-analytics:
    image: absenta-backend:latest
    container_name: absenta-worker-analytics
    env_file:
      - ../env/env.common
      - ../env/env.database
      - ../env/env.redis
      - ../env/env.production
    environment:
      - NODE_NAME=node-attendance
    command: ["node","dist/workers/analytics.worker.js"]

  worker-maintenance:
    image: absenta-backend:latest
    container_name: absenta-worker-maintenance
    env_file:
      - ../env/env.common
      - ../env/env.database
      - ../env/env.redis
      - ../env/env.production
    environment:
      - NODE_NAME=node-attendance
    command: ["node","dist/workers/maintenance.worker.js"]

networks:
  default:
    name: absenta-net
